# Generated by Django 5.0.3 on 2024-04-08 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_rename_created_by_item_create_by_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
