# Generated by Django 5.0.3 on 2024-04-12 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
