# Generated by Django 5.0.3 on 2024-04-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_remove_order_items_remove_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
