# Generated by Django 5.0.3 on 2024-04-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_order_additional_order_phone_number_order_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
