# Generated by Django 5.0.3 on 2024-04-13 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_alter_order_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='additional_order_phone_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_phone_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='receipt',
        ),
        migrations.AddField(
            model_name='order',
            name='additional_order_phone_number1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='city1',
            field=models.CharField(choices=[('Abia', 'Abia'), ('Adamawa', 'Adamawa'), ('Akwa Ibom', 'Akwa Ibom'), ('Anambra', 'Anambra'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Bayelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross River', 'Cross River'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Edo', 'Edo'), ('Ekiti', 'Ekiti'), ('Enugu', 'Enugu'), ('Gombe', 'Gombe'), ('Imo', 'Imo'), ('Jigawa', 'Jigawa'), ('Kaduna', 'Kaduna'), ('Kano', 'Kano'), ('Katsina', 'Katsina'), ('Kebbi', 'Kebbi'), ('Kogi', 'Kogi'), ('Kwara', 'Kwara'), ('Lagos', 'Lagos'), ('Nasarawa', 'Nasarawa'), ('Niger', 'Niger'), ('Ogun', 'Ogun'), ('Ondo', 'Ondo'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Rivers', 'Rivers'), ('Sokoto', 'Sokoto'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Zamfara', 'Zamfara')], default='Lagos', max_length=11),
        ),
        migrations.AddField(
            model_name='order',
            name='order_address1',
            field=models.CharField(default='Lagos', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='order_phone_number1',
            field=models.CharField(default='08038616626', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='receipt1',
            field=models.ImageField(default='images', upload_to='media/'),
        ),
    ]
