# Generated by Django 5.0.3 on 2024-04-13 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_alter_order_receipt1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='receipt1',
            new_name='receipt',
        ),
    ]
