# Generated by Django 5.0.3 on 2024-04-13 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0016_alter_order_receipt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
