# Generated by Django 5.0.3 on 2024-04-13 02:25

import item.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0018_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='receipt',
            field=models.ImageField(default=item.models.get_default_images, upload_to='media/'),
        ),
    ]
