# Generated by Django 5.0.3 on 2024-04-13 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0019_alter_order_receipt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='additional_order_phone_number1',
            new_name='additional_order_phone_number',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_address1',
            new_name='order_address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_phone_number1',
            new_name='order_phone_number',
        ),
    ]
