# Generated by Django 5.0.3 on 2024-04-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0020_rename_additional_order_phone_number1_order_additional_order_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
