# Generated by Django 5.0.3 on 2024-04-13 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0021_alter_order_order_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='city1',
            new_name='city',
        ),
        migrations.AlterField(
            model_name='order',
            name='additional_order_phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
